name: test

on:
  push:
    branches:
      - main
      - release/**
      - "*_dev"
    # does not work properly due to an issue in GitHub's branch protection
    # rules: https://github.com/orgs/community/discussions/13690
    # paths-ignore:
    #   - "conformance/**"
  pull_request:
    branches:
      - main
      - release/**
    # paths-ignore:
    #   - "conformance/**"
  merge_group:
  schedule:
    - cron: "0 3 * * 4"
  workflow_dispatch:

env:
  CARGO_WS_VERSION: "0.2.44"

jobs:
  ## Run all default oriented feature sets across all platforms.
  platform-matrix:
    name: platform
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [windows-latest]
    env:
      RUST_LOG: info,hickory_proto::udp::udp_stream=trace # Extra logging for issue #2649
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: extractions/setup-just@v2

      - name: cargo install cargo-workspaces
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-workspaces
          version: ${{ env.CARGO_WS_VERSION }}

      - run: netsh interface ipv4 show excludedportrange protocol=udp
      - run: netsh interface ipv6 show excludedportrange protocol=udp
